include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XFORMATS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Formats/xformats.cmake)
    set(XSTATICUNPACKER_SOURCES ${XSTATICUNPACKER_SOURCES} ${XFORMATS_SOURCES})
endif()
if (NOT DEFINED XARCHIVES_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XArchive/xarchives.cmake)
    set(XSTATICUNPACKER_SOURCES ${XSTATICUNPACKER_SOURCES} ${XARCHIVES_SOURCES})
endif()

set(XSTATICUNPACKER_SOURCES
    ${XSTATICUNPACKER_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xupx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xupx.h
)
