include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XFORMATS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Formats/xformats.cmake)
    set(XSTATICUNPACKER_SOURCES ${XSTATICUNPACKER_SOURCES} ${XFORMATS_SOURCES})
endif()
if (NOT DEFINED XARCHIVES_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XArchive/xarchives.cmake)
    set(XSTATICUNPACKER_SOURCES ${XSTATICUNPACKER_SOURCES} ${XARCHIVES_SOURCES})
endif()

set(XSTATICUNPACKER_SOURCES
    ${XSTATICUNPACKER_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xinnosetup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xinnosetup.h
    ${CMAKE_CURRENT_LIST_DIR}/xnsis.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnsis.h
    ${CMAKE_CURRENT_LIST_DIR}/xupx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xupx.h
    ${CMAKE_CURRENT_LIST_DIR}/xsfx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsfx.h
    ${CMAKE_CURRENT_LIST_DIR}/xfsg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfsg.h
    ${CMAKE_CURRENT_LIST_DIR}/xyoda.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xyoda.h
    ${CMAKE_CURRENT_LIST_DIR}/xnspack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnspack.h
    ${CMAKE_CURRENT_LIST_DIR}/xaspack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xaspack.h
    ${CMAKE_CURRENT_LIST_DIR}/xpetite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpetite.h
    ${CMAKE_CURRENT_LIST_DIR}/xmew.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmew.h
    ${CMAKE_CURRENT_LIST_DIR}/xpespin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpespin.h
    ${CMAKE_CURRENT_LIST_DIR}/xautoit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xautoit.h
)
